version: "3.1"

services:
  php-fpm:
    build:
      context: docker/php-fpm
    container_name: personal-webserver
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - WEB_DOCUMENT_ROOT=/app
    ports:
      - "80:80"
